services:
  backend:
    build: ./backend
    container_name: lailah_backend
    ports:
      - "8082:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - REDIS_HOST=redis
    networks:
      - lailah_network
  redis:
    image: "redis:alpine"
    container_name: lailah_redis
    ports:
      - "6379:6379"
    networks:
      - lailah_network

  db:
    image: "postgres:13"
    container_name: lailah_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lailah@123
      POSTGRES_DB: lailah
    ports:
      - "5432:5432"
    networks:
      - lailah_network

  frontend:
    build: ./frontend
    container_name: lailah_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - lailah_network

networks:
  lailah_network:
    driver: bridge

volumes:
  frontend_node_modules:
